### ISSUE TITLE
Error: shasum check failed

### ISSUE THREAD

**Issue by tywrr** [outmoded/postmile-web#2]
```
npm http 304 https://registry.npmjs.org/scarecrow
npm ERR! Error: shasum check failed for /var/folders/w0/hdphr_q90z70y49wdwjdm2t00000gn/T/npm-55803-QQmILInh/1397358651160-0.7151987534016371/tmp.tgz
npm ERR! Expected: 1ed37d9256785300f133707d2ad644c3a432df1f
npm ERR! Actual:   0bce44c540b2af1003b781fd4b13e678fdbcf4a1
npm ERR! From:     https://registry.npmjs.org/postmile-web/-/postmile-web-1.0.1.tgz
npm ERR!     at /usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "update"
npm ERR! cwd /Users/ty/code/postmile
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/catbot
```

When doing `npm update` on hueniverse/postmile this is the only package that has an shasum error. postmile-web.
Getting this error on three different system, three different versions of Node and on two different networks. Have yet to figure out why.

**Comment by henry-hz** [comment]
Having the same issue, please, help.

**Comment by hueniverse** [comment]
That was a bug in node/npm. Now working.
